### ISSUE TITLE
Split Luxon.re into a few modules

### ISSUE THREAD

**Issue by davidgomes** [davidgomes/bs-luxon#2]
Right now, bs-luxon clients have to use it like this:

```ocaml
let dt = BsLuxon.Luxon.DateTime.local();

Js.log(dt);
```

We should refactor DateTime into its own module so users can use it like this instead:

```ocaml
let dt = BsLuxon.DateTime.local();

Js.log(dt);
```

**Comment by davidgomes** [comment]
@Thomas0c please let me know if you would prefer this instead for your project. It's an easy fix.

**Comment by Thomas0c** [comment]
Definitely. Minor change, but makes it cleaner and facilitates keeping things modular in the future.

**Comment by davidgomes** [comment]
Done!
