### ISSUE TITLE
update README - open BsLuxon

### ISSUE THREAD

**Issue by codekiln** [davidgomes/bs-luxon#6]
Thanks for making `bs-luxon`! The front page has an example of using it:

```
DateTime.(
  local()
  |> setZone("America/New_York")
  |> minus(`Duration(Duration.from(~weeks=1, ())))
  |> endOf(`day)
  |> toISO()
);
```

I think this should have `open BsLuxon;` at the top, since that's what I needed to do in order to get it to compile; pointing this out for others that want to use the library. See [here for an example of using it in a project](https://github.com/codekiln/hlibhours/blob/master/api/LibraryAPI.re#L127).

**Comment by rjhilgefort** [comment]
Hit this as well. Having that in the README would be beneficial. I was looking at the examples and didn't see the `open` in the `demo.re` either. I couldn't figure out what I was doing wrong.

**Comment by davidgomes** [comment]
That namespace is not defined by `bs-luxon` anywhere, I think some part of the Reason toolchain automatically generates that name, but I can't say for sure (and I couldn't find documentation about this anywhere). I recommend that you try to ask this question in the [ReasonML Discord](https://discord.gg/reasonml).

**Comment by mikaello** [comment]
This is documented in the [configuration section of the Bucklescript documentation](https://bucklescript.github.io/docs/en/build-configuration#name-namespace):

> **Note**: the `bsconfig.json` `name` should be the same as the `package.json` `name`, to avoid confusing corner-cases. However, this means that you can't use a camelCased names such as `MyProject`, since `package.json` and npm forbid you to do so (some file systems are case-insensitive). To have the namespace/module as `MyProject`, write `"name": "my-project"`. Bsb will turn that into the camelCased name correctly.

So it is bsb that transforms `bs-luxon` to `BsLuxon`. I think [this is the code that performs this transformation](https://github.com/BuckleScript/bucklescript/blob/f222f1e3abc85db42ad25b430a5148eccea9d356/lib/bsb.ml#L9111-L9136): 

```ocaml
let namespace_of_package_name (s : string) : string = 
  let len = String.length s in 
  let buf = Buffer.create len in 
  let add capital ch = 
    Buffer.add_char buf 
      (if capital then 
         (Ext_char.uppercase_ascii ch)
       else ch) in    
  let rec aux capital off len =     
    if off >= len then ()
    else 
      let ch = String.unsafe_get s off in
      match ch with 
      | 'a' .. 'z' 
      | 'A' .. 'Z' 
      | '0' .. '9'
        ->
        add capital ch ; 
        aux false (off + 1) len 
      | '/'
      | '-' -> 
        aux true (off + 1) len 
      | _ -> aux capital (off+1) len
  in 
  aux true 0 len ;
  Buffer.contents buf 
```

**Comment by rjhilgefort** [comment]
This is great @mikaello!! Thanks for taking the time to respond and share that info!
